#!/bin/sh

n=$(cat /sys/class/power_supply/BAT0/capacity)
m=$(cat /sys/class/power_supply/BAT1/capacity)

sum=$(($n+$m))
ans=$(($sum / 2))

if [ "$ans" -gt 97 ]; then
   icon="   "
elif [ "$ans" -gt 75 ]; then
    icon="   "
elif [ "$ans" -gt 50 ]; then
    icon="   "
elif [ "$ans" -gt 25 ]; then
    icon="   "
elif [ "$ans" -gt 10 ]; then
    icon="   "
else
    icon="   "
fi



echo -e "%{B#707880}%{F#1d1f21}${icon}%{F#1d1f21} %{B#c5c8c6} BAT ${ans} % "
