#!/bin/bash

PREFIX_PLAY=' '
PREFIX_PAUSE=' '

get_mpd()
{
	current_song="$(mpc current)"

	if [[ "$current_song" = "" ]]; then
		echo " %{B#a54242} %{F#1d1f21}   "
		exit 0
	else
		playpause=$(mpc | awk '/\[.*]/{split($0, a, " "); print a[1]}')
		if [[ "$playpause" = "[playing]" ]]; then
			current_song="%{B#a54242} %{F#1d1f21} $PREFIX_PLAY %{B#cc6666}%{F#1d1f21} $current_song"
		elif [[ "$playpause" = "[paused]" ]]; then
			current_song="%{B#a54242} %{F#1d1f21} $PREFIX_PAUSE%{B#cc6666}%{F#1d1f21} $current_song"
		fi
	fi

	echo " %{B#cc6666}%{F#1d1f21}$current_song "
}

get_mpd

